const fs = require('fs');
const path = require('path');

const palette = {
  '.': 'none',
  'H': '#412d45', // Hat Hi
  'h': '#281a2b', // Hat Base
  'D': '#140c17', // Hat Dark/Outline
  'S': '#f0d9c7', // Skin Hi
  's': '#ccab97', // Skin Base
  'a': '#9c7764', // Skin Shadow
  'W': '#ffffff', // Eye White
  'E': '#3b9ca3', // Eye Iris (cyan/teal glowing)
  'o': '#9e223a', // Red Eye Iris (for angry/hurt)
  'R': '#e83858', // Scarf Hi
  'r': '#a8203c', // Scarf Base
  'd': '#631122', // Scarf Shadow
  'C': '#44384a', // Coat Hi
  'c': '#2b232e', // Coat Base
  'k': '#1a141b', // Coat Dark
  'G': '#f0c756', // Gold Hi
  'g': '#a88122', // Gold Base
  'B': '#110d12', // Boots
  'b': '#bd152e', // Blood 1
  'v': '#7a0a1a'  // Blood 2
};

const f0 = `
..........DhhD..........
........DhhhhhhD........
.......DhhHhhHhhD.......
......DDDhhhhhhDDD......
.....DDDDDDDDDDDDDD.....
.......sSSSSSSSSs.......
.......aWEsSSsEWa.......
.......aSSSssSSSa.......
........arrrrrra........
.......rrRRRRrrrr.......
......drrrrrrrrrrd......
......kcccccCcccck......
.....cckCcccccckckcc....
....ss..kccGgcck..ss....
....ss..kkcgGckk..ss....
........kcccckck........
........BB...BB.........
.......BBB...BBB........
`;

const f1 = `
..........DhhD..........
........DhhhhhhD........
.......DhhHhhHhhD.......
......DDDhhhhhhDDD......
.....DDDDDDDDDDDDDD.....
.......sSSSSSSSSs.......
.......aWEsSSsEWa.......
.......aSSSssSSSa.......
........arrrrrra........
........rRRRRrrr........
.......drrrrrrrrd.......
......kcccccCcccck......
.....cckCcccccckckcc....
....ss..kccGgcck..ss....
....ss..kkcgGckk..ss....
........kkcckkck........
........BB...BB.........
.......BBB...BBB........
`;

const wd1 = `
..........DhhD..........
........DhhHhhhD........
.......DhhhhhhHhD.......
......DDDhhhhhhDDD......
.....DDDDDDDDDDDDDD.....
.......sSSSSSSSSs.......
.......aWEsSSsEWa.......
.......aSSSssSSSa.......
........drrrrrd.........
.......rrRRRRrrrr.......
......drrrrrrrrrrd......
.....cckcccCccccck......
....ss.kCcccccckckc.....
....ss..kccGgcck..ss....
........kkcgGckk........
........kcccck..........
........BB...kk.........
.......BBB...BB.........
.............BBB........
`;

const wd2 = f1;

const wd3 = `
..........DhhD..........
........DhhhHhhD........
.......DhHhhhhhhD.......
......DDDhhhhhhDDD......
.....DDDDDDDDDDDDDD.....
.......sSSSSSSSSs.......
.......aWEsSSsEWa.......
.......aSSSssSSSa.......
........drrrrrd.........
.......rrrrRRRRrr.......
......drrrrrrrrrrd......
......kcccccCcccbcc.....
.....ckckccccccCk.ss....
....ss..kccGgcck..ss....
........kkcgGckk........
..........kcccck........
........kk...BB.........
........BB...BBB........
.......BBB..............
`;

const rs0 = `
...........DhhD.........
.........DhhhhhD........
........DhhhhhHhD.......
.......DDhhhhhhDD.......
.......DDDDDDDDDDD......
.........sSSSSS.........
.........SSaWEs.........
........sSSssss.........
.........arrrra.........
.......drrRRRRr.........
.......drrrrrrrd........
......ckccccCcck........
.....ssscckCccc.........
.....sss..kcGgck........
..........kcgGck........
.........kccckk.........
.........BB..BB.........
........BBB..BBB........
`;

const rs1 = `
...........DhhD.........
.........DhhhhhD........
........DhhhhhHhD.......
.......DDhhhhhhDD.......
.......DDDDDDDDDDD......
.........sSSSSS.........
.........SSaWEs.........
........sSSssss.........
.........arrrra.........
.......drrRRRRr.........
.......drrrrrrrd........
......ckccccCcck........
.....ssscckCccc.........
.....sss..kcGgck........
..........kcgGck........
..........kk.kkk........
...........BB...........
..........BBB.BB........
..............BBB.......
`;

const rs2 = `
...........DhhD.........
.........DhhhhhD........
........DhhhhhHhD.......
.......DDhhhhhhDD.......
.......DDDDDDDDDDD......
.........sSSSSS.........
.........SSaWEs.........
........sSSssss.........
.........arrrra.........
.......drrRRRRr.........
.......drrrrrrrd........
......ckccccCcck........
.....ssscckCccc.........
.....sss..kcGgck........
..........kcgGck........
.........kccckk.........
..........BB............
.........BBB............
`;

const rs3 = `
...........DhhD.........
.........DhhhhhD........
........DhhhhhHhD.......
.......DDhhhhhhDD.......
.......DDDDDDDDDDD......
.........sSSSSS.........
.........SSaWEs.........
........sSSssss.........
.........arrrra.........
.......drrRRRRr.........
.......drrrrrrrd........
......ckccccCcck........
.....ssscckCccc.........
.....sss..kcGgck........
..........kcgGck........
........kkck.kk.........
.......BB....BB.........
......BBB....BBB........
`;

const up0 = `
..........DhhD..........
........DhhhhhHhD.......
.......DhhhhhhhHhD......
......DDhhhhhhhHhDD.....
.....DDDDDDDDDDDDDDD....
.......cccccccccc.......
.......cccccccCcc.......
.......cccccccccc.......
........kcccckck........
........kcccckck........
.......ckcccckckc.......
......ckccccCckckc......
.....cckccccCckckcc.....
....cc..kccCccc...cc....
....cc..kkcccCk...cc....
........kcccckc.........
........BB...BB.........
.......BBB...BBB........
`;

const upw1 = `
..........DhhD..........
........DhhhhhHhD.......
.......DhhhhhhhHhD......
......DDhhhhhhhHhDD.....
.....DDDDDDDDDDDDDDD....
.......cccccccccc.......
.......cccccccCcc.......
.......cccccccccc.......
........kcccckck........
........kcccckck........
.......ckcccckckc.......
......ckccccCckckc......
.....cckccccCckckcc.....
....cc..kccCccc...cc....
........kkcccCkc........
........kcc..kk.........
........BB..............
.......BBB...BB.........
.............BBB........
`;

const up1 = `
..........DhhD..........
........DhhhhhHhD.......
.......DhhhhhhhHhD......
......DDhhhhhhhHhDD.....
.....DDDDDDDDDDDDDDD....
.......cccccccccc.......
.......cccccccCcc.......
.......cccccccccc.......
........kcccckck........
........kcccckck........
.......ckcccckckc.......
......ckccccCckckc......
.....cckccccCckckcc.....
....cc..kccCccc...cc....
....cc..kkcccCk...cc....
........kc...kc.........
........BB...BB.........
.......BBB...BBB........
`;

const upw3 = `
..........DhhD..........
........DhhhhhHhD.......
.......DhhhhhhhHhD......
......DDhhhhhhhHhDD.....
.....DDDDDDDDDDDDDDD....
.......cccccccccc.......
.......cccccccCcc.......
.......cccccccccc.......
........kcccckck........
........kcccckck.......
.......ckcccckckc.......
......ckccccCckckc......
.....cckccccCckckcc.....
....cc..kccCccc...cc....
........kkcccCkc........
.........kk..cck........
..............BB........
.........BB..BBB........
........BBB.............
`;

const hurt0 = `
.........DhhD...........
.......DhhhhhHhD........
......DhhhhhhhHhD.......
.....DDhhhhhhhHhDD......
....DDDDDDDDDDDDDDD.....
......SaaSSSaaaS........
......oWEoSSoEWo........
......SaaSSaSSaS........
.......drrrRrrra........
.......drRbvbrr.........
......ckrbbvbvrc........
.....cckCcvbcCc.ss......
.....cc.kcGgcCk.ss......
........kcGgcCk.........
.........cckcck.........
........BB...B..........
.......BBB..BB..........
`;

const d0 = hurt0;

const d1 = `
..........hHh...........
........DhhhHhD.........
.......DhhhhHhhD........
......DDhhhhHhhhD.......
......DDDDDDDDDDD.......
.......aaSaaaSSs........
........oWSoSWo.........
.......aaSSSSaa.........
.......dvrrrRrd.........
......cvrcRrbdv.........
.....cccvbbrcd..ss......
....ccckbGgck...ss......
.......kGgckk...........
......B.kk...B..........
.....BBB....BBB.........
`;

const d2 = `
..........hHHh..........
........DhhhhhD.........
.......DhhhHhhhD........
.......DDhhhhhhD........
........DDDDDDDD........
........aSaaaSS.........
........oSoSWo..........
........aSSaS...........
.......vbrrRrd..........
......cvrcrrbv..........
.....cckbbbbck..........
...ss..GgkkGg...ss......
.......k...BB...........
......BB..BBB...........
.....BBB................
`;

const d3 = `
........hHHh............
......SDhhhhD...........
......WoSohhhD..........
......SddhHhhhD.........
.....svbbbhhhhDD........
....sscrrDDDDDDD........
.....cbbGgk.............
...ccbbGgck.............
..BBbkkck.BB............
..BBBBBB..BBB...........
`;

const d4 = `
.......hhhD.............
.....aSddhhhD...........
...ssvbbbdhhhD..........
...cbvbbvDDDDDD.........
..cbbbGgckc.............
.BBbkkB..BB.............
.BBB.....BBB............
`;

const d5 = `
......D.DD.D............
...v.vbvbbbdd.D.........
..vvvbbbvvbrDD..........
.BkkvBB...BB............
.BBB......BBB...........
`;

const frames = [
  // row 0: idle down (2 frames) -> 0..5
  f0, f1, null, null, null, null,
  // row 1: walk down (4)
  wd1, wd2, wd3, wd2, null, null,
  // row 2: idle side (right) (2)
  rs0, rs2, null, null, null, null,
  // row 3: walk side (right) (4)
  rs1, rs2, rs3, rs2, null, null,
  // row 4: idle up (2)
  up0, up1, null, null, null, null,
  // row 5: walk up (4)
  upw1, up0, upw3, up0, null, null,
  // row 6: hurt (4)
  hurt0, hurt0, hurt0, hurt0, null, null,
  // row 7: death (6)
  d0, d1, d2, d3, d4, d5
];

function parseAscii(str) {
  if (!str) return [];
  const lines = str.trim().split(/[\r\n]+/).map(l => l.trim()).filter(l => l.length > 0);
  const rows = [];
  // Ensure lines are centered or at least properly mapped.
  // The y-offset starts so that the 18th body row aligns with Y=20 roughly.
  // Actually, we align bottom line to ~Y=19
  const height = lines.length;
  const startY = 21 - height; 
  
  for(let y=0; y<height; y++) {
    const line = lines[y];
    for(let x=0; x<line.length; x++) {
      const ch = line[x];
      if (ch !== '.') {
        rows.push({ x: x, y: startY + y, fill: palette[ch] });
      }
    }
  }
  return rows;
}

const finalWidth = 144;
const finalHeight = 192;

let svgOut = '<svg xmlns="http://www.w3.org/2000/svg" width="' + finalWidth + '" height="' + finalHeight + '" viewBox="0 0 ' + finalWidth + ' ' + finalHeight + '" shape-rendering="crispEdges">\n' +
  '  <defs>\n' +
  '    <style>\n' +
  '      .bg { fill: none; }\n' +
  '    </style>\n' +
  '  </defs>\n' +
  '  <rect class="bg" x="0" y="0" width="' + finalWidth + '" height="' + finalHeight + '" />\n';

frames.forEach((ascii, i) => {
  if (!ascii) return; // empty slot
  
  const col = i % 6;
  const row = Math.floor(i / 6);
  
  const offsetX = col * 24;
  const offsetY = row * 24;
  
  const pixels = parseAscii(ascii);
  
  // Group by color to minimize dom elements
  const byColor = {};
  pixels.forEach((p) => {
    byColor[p.fill] = byColor[p.fill] || [];
    byColor[p.fill].push(p);
  });
  
  svgOut += '  <g id="frame_' + row + '_' + col + '" transform="translate(' + offsetX + ' ' + offsetY + ')">\n';
  
  for (const color in byColor) {
    let d = '';
    byColor[color].forEach((p) => {
      d += 'M' + p.x + ' ' + p.y + 'h1v1h-1z ';
    });
    if (color !== "undefined") {
      svgOut += '    <path fill="' + color + '" d="' + d.trim() + '" />\n';
    }
  }
  svgOut += '  </g>\n';
});

svgOut += '</svg>\n';

function optimizeSVGPaths(svg) {
   return svg;
}

fs.writeFileSync(path.join(__dirname, 'assets', 'characters', 'player-sheet-refined-v2.svg'), optimizeSVGPaths(svgOut), 'utf8');
console.log('Player sheet generated successfully at assets/characters/player-sheet-refined-v2.svg !');
