const fs = require('fs');
const path = require('path');

const palette = {
  '.': 'none',
  's': '#a0c49d', // Skin High
  'S': '#699965', // Skin Base
  'a': '#3a6639', // Skin Shadow
  'A': '#243b23', // Skin Dark
  'C': '#607985', // Clothes High
  'c': '#435863', // Clothes Base
  'k': '#28363d', // Clothes Shadow
  'K': '#141d21', // Clothes Dark
  'e': '#ff2a3a', // Eye Bright
  'E': '#a61120', // Eye Dark
  'B': '#e1d7aa', // Bone/Teeth
  'O': '#0b0f0b'  // Outline
};

const f0 = `
..........OOOO..........
........OOaSSaOO........
.......OsSSeSSSsaO......
......OaSeeeaSaaAAO.....
......OAaEEAaAaAaaO.....
.....OOkABBBBAASAcSO....
....OaAoAaAAAAackkKkO...
....OsAOcKcccCCccCckO...
....OAaOckkcccccCcKkO...
.....OOOckCcccccccckcO..
.......OkkcccckcccCcKkO.
......SskKkcccKkckKkcK..
......AakKkccKk.kKKkkcO.
.......OKCCkck...cKCkK..
.......OkkKkKO...KkKkO..
........OOO......AOO....
.......AAS.......aS.....
.......OOA.......OOA....
`;

const f1 = `
..........OOOO..........
........OOaSSaOO........
.......OsSSeSSSsaO......
......OaSeeeaSaaAAO.....
......OAaEEAaAaAaaO.....
.....OOkABBBBAASAcSO....
....OaAoAaAAAAackkKkO...
....OsAOcKcccCCccCckO...
....OAaOckkcccccCcKkO...
.....OOOckCcccccccckcO..
.......OkkcckKkcCcKkO...
......SskKccCcKkKkckK...
......AakKkKk.kKKkkcO...
.......OKCCkOKcCCkK.....
........kkKkOkkKkO......
........OOO...AOO.......
.......AAS....aS........
.......OOA....OOA.......
`;

const wd1 = `
..........OOOO..........
........OOaSSaOO........
.......OsSSeSSSsaO......
......OaSeeeaSaaAAO.....
......OAaEEAaAaAaaO.....
.....OOkABBBBAASAcSO....
....OaAoAaAAAAackkKkO...
....OsAOcKcccCCccCckO...
....OAaOckkcccccCcKkO...
.....OOOckCcccccccckcO..
.......OkkcccckccCCcKkO.
......SskKkcccKkKckKckO.
......AakKkccKk...kKKkK.
.......OKCCkck...OOOOk..
.......OkkKkKO..AASkO...
.......OOOOO....OOAO....
......SsaA............
......oAOOO.............
`;

const wd2 = f1;

const wd3 = `
..........OOOO..........
........OOaSSaOO........
.......OsSSeSSSsaO......
......OaSeeeaSaaAAO.....
......OAaEEAaAaAaaO.....
.....OOkABBBBAASAcSO....
....OaAoAaAAAAackkKkO...
....OsAOcKcccCCccCckO...
....OAaOckkcccccCcKkO...
.....OOOckCcccccccckcO..
.......OkkcccckckKCcKkO.
......OKkKkckKcccKkKksS.
......KkKKkK...kKccKkaA.
.......kOOOO...kckCCKO..
.......OkSAA..OKkKkkO...
.......OAOOO..OOOOO.....
..............AaSS......
..............OOAO......
`;

const rs0 = `
...........OOOO.........
.........OOaSSsO........
........OaaSSeeSO.......
.......OaaASaeEeO.......
.......OAaASSBBAO.......
........OAaaaAAaO.......
.......OOckkKkkkcO......
......OcKcccCcccckO.....
......ckccccccCcKcco....
.....OckkccccCckckKkO...
.....cKkcccccckCcckAc...
....OcKccckcccckckAasO..
....KkcKKkkKkccccOsAOO..
....KcccK.O.KKKkKO.OO...
....KkKkO...OKCCkO......
.....OOO.....kKkKO......
.....AAS.....AASO.......
.....OOA.....AOO........
`;

const rs2 = `
...........OOOO.........
.........OOaSSsO........
........OaaSSeeSO.......
.......OaaASaeEeO.......
.......OAaASSBBAO.......
........OAaaaAAaO.......
.......OOckkKkkkcO......
......OcKcccCcccckO.....
......ckccccccCcKcco....
.....OckkccccCckckKkO...
.....cKkcccccckCcckAc...
....OcKccckcccckckAasO..
....KkcKKkkKkccccOsAOO..
....KcccK.O.KKKkKO.OO...
....KkKkO...OKCCkO......
.....OOO.....AASO.......
.....AAS.....AOO........
.....OOA................
`;

const rs1 = `
...........OOOO.........
.........OOaSSsO........
........OaaSSeeSO.......
.......OaaASaeEeO.......
.......OAaASSBBAO.......
........OAaaaAAaO.......
.......OOckkKkkkcO......
......OcKcccCcccckO.....
......ckccccccCcKcco....
.....OckkccccCckckKkO...
.....cKkcccccckCcckAc...
....OcKccckcccckckAasO..
....KkcKKkkKkccccOsAOO..
....KcccK.O.KKKkKO.OO...
....KkKkO...OAASkO......
.....OOO.....kOOO.......
.....AAS................
.....OOA................
`;

const rs3 = `
...........OOOO.........
.........OOaSSsO........
........OaaSSeeSO.......
.......OaaASaeEeO.......
.......OAaASSBBAO.......
........OAaaaAAaO.......
.......OOckkKkkkcO......
......OcKcccCcccckO.....
......ckccccccCcKcco....
.....OckkccccCckckKkO...
.....cKkcccccckCcckAc...
....OcKccckcccckckAasO..
....KkcKKkkKkccccOsAOO..
....KcccK.O.KKKkKO.OO...
....KkKkO...OKCCkO......
.....AASO....kKkKO......
.....AOOO....AASO.......
.............AOO........
`;

const up0 = `
..........OOOO..........
........OOAaaSsO........
.......OaAAAAAASO.......
......OaAaaaaAaAOO......
......OaAaAAAAaaAO......
.....OOkkkkkkkkKckO.....
....OcKccKkkccKcckcO....
....OcCckcCcCcCcKkCO....
....OkKcccCCCcckKkcO....
.....OOccKcccKckcckO....
.......kcccCKCccKkKO....
......CKkcCCcCckccckO...
......cKcKkCccccKcckO...
.......ckkcKkkkCccKkO...
.......OKkOkkKKKccKK....
........OOO......OkO....
.......AAS.......aS.....
.......OOA.......OOA....
`;

const up1 = `
..........OOOO..........
........OOAaaSsO........
.......OaAAAAAASO.......
......OaAaaaaAaAOO......
......OaAaAAAAaaAO......
.....OOkkkkkkkkKckO.....
....OcKccKkkccKcckcO....
....OcCckcCcCcCcKkCO....
....OkKcccCCCcckKkcO....
.....OOccKcccKckcckO....
.......OcccCKCccKkKO....
......CkccCCcCckcccko...
......cKcKkCccccKcckO...
.......KkKkKkkkCccKkO...
.......OKkO..OKKccKK....
........OOO...OO...O....
.......AAS....aS........
.......OOA....OOA.......
`;

const upw1 = `
..........OOOO..........
........OOAaaSsO........
.......OaAAAAAASO.......
......OaAaaaaAaAOO......
......OaAaAAAAaaAO......
.....OOkkkkkkkkKckO.....
....OcKccKkkccKcckcO....
....OcCckcCcCcCcKkCO....
....OkKcccCCCcckKkcO....
.....OOccKcccKckcckO....
.......OcccCKCccKKO.....
......CkccCCcCccKkccO...
......cKcKkCcccKKOAas...
.......KkKkKkKkcMOAOO...
.......OKkO...OAASO.....
........OOO...OOOO......
.......AAS..............
.......OOA..............
`;

const upw3 = `
..........OOOO..........
........OOAaaSsO........
.......OaAAAAAASO.......
......OaAaaaaAaAOO......
......OaAaAAAAaaAO......
.....OOkkkkkkkkKckO.....
....OcKccKkkccKcckcO....
....OcCckcCcCcCcKkCO....
....OkKcccCCCcckKkcO....
.....OOccKcccKckcckO....
.......OKKccCKCcKkKO....
......OccKkcccCCcKccO...
.....saAOKKcccKkCkcKo...
.....OOAOMckKkKkKkKkO...
.....OSAOO...OKkOO......
......OOOO...OOO........
..............AAS.......
..............OOA.......
`;

const hurt0 = `
.........OOOO...........
.......OOaaAaOO.........
......OaasAaSAsaO.......
.....OaEeaSaAEeaAO......
.....OAEeeeEeeeEaO......
....OoKBAEBaABEASaO.....
...OaAoAaaaaAAAakkkO....
...OsAOcKcccccCcKckO....
...OAaOcKcbbbccKccccO...
....OOOckvBbBvKkkvvcO...
......OkkvbBvvcCcbbko...
.....SskKkcbvvbbbvvkK...
.....AakKkcKb.vvbkbcO...
......OKCCkc...cKCcK....
......OkkKkKO...KkKKO...
.......OOO......AOO.....
......AAS.......aS......
......OOA.......OOA.....
`;

const d0 = hurt0;

const d1 = `
..........OOOO..........
........OAasAaO.........
.......OaaSSeaAO........
......AaEeAaAEeaAO......
......OeEEEcEEEeOO......
.......oKBBcaBEsAoO.....
........kbbCaaAAOO......
.......obvbbbCcAaS......
.......cvBbbBvcAOO......
......ccCvvvbvvkocO.....
.....cAkvbvBBvvcO.......
....sAOkKbvbvckk........
....aAOkckkvcOk.........
......B.kkB.B...........
.....OBA.OOAAO..........
`;

const d2 = `
..........OOOO..........
........OAasAaO.........
.......AaaSSeAAO........
.......AaeAAaeAO........
.......OeEcKceEO........
.......OKBBvkBsAO.......
.......kKvbbbbcvO.......
.......cvBbbBvkcO.......
......OcCcvvbvcAaS......
.....CcAkvcbBvcAOO......
....sAO.KkbvbvkO........
....aAO.ckkvcOk.........
.......kkkcOKkO.........
......BA.k.B...........
.....OBA.OOOAO..........
`;

const d3 = `
........OOOO............
......OOAAAaO...........
......EoAoAAaO..........
......oEAkccaAO.........
.....avbbbcAkAAA........
....OasckOkckccO........
.....abbBbvOOO..........
...O.kcbBbvO............
..SOBkkkck.AB...........
..AASaSO..SaS...........
..OOaOO....OO...........
`;

const d4 = `
.......AAAO.............
.....aAddAAaO...........
...ssobvbbAaaO..........
...cAobvvbOOOOO.........
..cbbbBbvcAOO...........
.SABkkkS..aS............
.AOa.O....OOO...........
`;

const d5 = `
......O.OO.O............
...v.vbvbbbdd.O.........
..vvvbbbvvbroO..........
.SkkvAS...aS............
.AO.......OOO...........
`;

const frames = [
  // row 0: idle down (col 0, 1)
  f0, f1, null, null,
  // row 1: walk down (col 0, 1, 2, 3)
  wd1, wd2, wd3, wd2,
  // row 2: idle side (col 0, 1)
  rs0, rs2, null, null,
  // row 3: walk side (col 0, 1, 2, 3)
  rs1, rs2, rs3, rs2,
  // row 4: idle up (col 0, 1)
  up0, up1, null, null,
  // row 5: walk up (col 0, 1, 2, 3)
  upw1, up0, upw3, up0,
  // row 6: death (col 0, 1, 2, 3)
  d2, d3, d4, d5
];

function parseAscii(str) {
  if (!str) return [];
  const lines = str.trim().split(/\r?\n/).map(l => l.trim()).filter(l => l.length > 0);
  const rows = [];
  const height = lines.length;
  const startY = 24 - height; 
  
  for(let y=0; y<height; y++) {
    const line = lines[y];
    for(let x=0; x<line.length; x++) {
      const ch = line[x];
      if (ch !== '.') {
        const hcol = palette[ch] || palette['O']; // default to outline if unsupported
        rows.push({ x: x, y: startY + y, fill: hcol });
      }
    }
  }
  return rows;
}

const finalWidth = 96;
const finalHeight = 168;

let svgOut = '<svg xmlns="http://www.w3.org/2000/svg" width="' + finalWidth + '" height="' + finalHeight + '" viewBox="0 0 ' + finalWidth + ' ' + finalHeight + '" shape-rendering="crispEdges">\n' +
  '  <defs>\n' +
  '    <style>\n' +
  '      .bg { fill: none; }\n' +
  '    </style>\n' +
  '  </defs>\n' +
  '  <rect class="bg" x="0" y="0" width="' + finalWidth + '" height="' + finalHeight + '" />\n';

frames.forEach((ascii, i) => {
  if (!ascii) return; 
  const col = i % 4;
  const row = Math.floor(i / 4);
  const offsetX = col * 24;
  const offsetY = row * 24;
  
  const pixels = parseAscii(ascii);
  const byColor = {};
  pixels.forEach((p) => {
    byColor[p.fill] = byColor[p.fill] || [];
    byColor[p.fill].push(p);
  });
  
  svgOut += '  <g id="frame_' + row + '_' + col + '" transform="translate(' + offsetX + ' ' + offsetY + ')">\n';
  for (const color in byColor) {
    let d = '';
    byColor[color].forEach((p) => {
      d += 'M' + p.x + ' ' + p.y + 'h1v1h-1z ';
    });
    if (color !== "undefined") {
      svgOut += '    <path fill="' + color + '" d="' + d.trim() + '" />\n';
    }
  }
  svgOut += '  </g>\n';
});

svgOut += '</svg>\n';

fs.writeFileSync(path.join(__dirname, 'assets', 'characters', 'zombie-sheet-refined-v2.svg'), svgOut, 'utf8');
console.log('Zombie sheet generated successfully at assets/characters/zombie-sheet-refined-v2.svg !');

